-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.author
(
    author_id INTEGER NOT NULL,
    first_name character varying(80) NOT NULL,
    last_name character varying(80) NOT NULL,
    birth_year integer NOT NULL,
    death_year integer,
	CONSTRAINT "Author_pkey" PRIMARY KEY (author_id)
);

CREATE TABLE IF NOT EXISTS public.exhibit
(
    exhibit_id integer NOT NULL,
    name character varying(80) NOT NULL,
    type character varying(80) NOT NULL,
    year integer NOT NULL,
    materials character varying(80) NOT NULL,
    author_id integer NOT NULL,
    CONSTRAINT "Exhibit_pkey" PRIMARY KEY (exhibit_id),
	CONSTRAINT fk_author FOREIGN KEY (author_id)
        REFERENCES public.author (author_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.room
(
    room_id integer NOT NULL,
    floor integer NOT NULL,
    name character varying(80) NOT NULL,
    time_start time(4) without time zone,
    time_end time(4) without time zone,
    CONSTRAINT "Room_pkey" PRIMARY KEY (room_id)
);

CREATE TABLE IF NOT EXISTS public.placement
(
    exhibit_id INTEGER NOT NULL,
    room_id INTEGER NOT NULL,
    CONSTRAINT fk_exhibit FOREIGN KEY (exhibit_id)
        REFERENCES exhibit(exhibit_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_room FOREIGN KEY (room_id)
        REFERENCES room(room_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

ALTER TABLE IF EXISTS public.exhibit
    ADD FOREIGN KEY (author_id)
    REFERENCES public.author (author_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.placement
    ADD FOREIGN KEY (exhibit_id)
    REFERENCES public.exhibit (exhibit_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.placement
    ADD FOREIGN KEY (room_id)
    REFERENCES public.room (room_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;